verbose: true

spawnRadius: 40
flyBoostMultiplier: 2
startBoostMultiplier: 1.2
world: world

boostSoundSetter: true
# if boostSoundSetter is "true"
boostSound: entity.breeze.wind.burst

switchGamemodeCancelSoundSetter: true
# if swiitchGamemodeCancelSoundSetter is "true"
switchGamemodeCancelSound: block.anvil.destroy

particle: true

# elytra activation mode
doubleJump: true
fall: false

#fall mode settings
fallThreshold: 2