verbose: true # for idiots

spawnRadius: 40
flyBoostMultiplier: 2
startBoostMultiplier: 1.2
world: world
boostSound: true
boostSoundVolume: 10 # 0 = false
boostSoundSetter: true
boostSound: entity.breeze.wind.burst
boostSoundPitch: 2
switchGamemodeCancelSound: true
# if swiitchGamemodeCancelSound is "true"
switchGamemodeCancelSoundVolume: 10 # 0 = flase
switchGamemodeCancelSoundSetter: true
switchGamemodeCancelSound: block.anvil.destroy
switchGamemodeCancelSoundPitch: 2
particle: true