verbose: true # for idiots

spawnRadius: 40
flyBoostMultiplier: 2
startBoostMultiplier: 1.2
world: world

boostSoundSetter: true
# if boostSoundSetter is "true"
boostSound: entity.breeze.wind.burst
boostSoundVolume: 10
boostSoundPitch: 2

switchGamemodeCancelSoundSetter: true
# if swiitchGamemodeCancelSoundSetter is "true"
switchGamemodeCancelSound: block.anvil.destroy
switchGamemodeCancelSoundVolume: 10
switchGamemodeCancelSoundPitch: 2

particle: true